### ISSUE TITLE
automatic audio provider switch too aggressive

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#139]
A clip name with mp3 suffix triggers an attempt to load the audio plugin even if `http` is specified explicitly as provider by the user.
This is the reason why aac shoutcast streams do not work:
http://flowplayer.blacktrash.org/test/shoutcast.html
Their filenames end in `.mp3`.

See also: http://flowplayer.org/forum/#!/embedding_analytics#want-your-reader-to-a-web-r

@anssip - as it might be difficult to decide whether `http` is just the silent default for provider or whether it was explicitly given, and as the cases are rather rare where an `.mp3` suffix does _not_ indicate, well, an MP3 file, we should be careful not to destroy the current logic - maybe require to additionally specify `null` as the value for the audio plugin or some such ...

**Comment by anssip** [comment]
Fixed version in the dev site.

**Comment by phloxic** [comment]
That would be 3.2.17-dev of core?
No, I can still see the exact same problem: http://flowplayer.blacktrash.org/test/shoutcast.html (2nd player)- console says it tries to load audio plugin.

**Comment by anssip** [comment]
I don't think the 2nd player loads the audio plugin. This returns undefined 

$f("aac").getPlugin("audio")

Also if you look at the console's network tab you see that the audio plugin is loaded only once. (The controls plugin is loaded twice, for example, by both players)

**Comment by phloxic** [comment]
Yep, sorry.
Unfortunately it's not a solution for the actual problem because the stream is not found. Will double check whether aac files can be played on demand via http.

**Comment by phloxic** [comment]
I have not found a way to play "raw" aac files - i.e. adts - streams.
AAC needs to be in an MP4 container - then it works both via http and rtmp: http://flowplayer.blacktrash.org/test/aac.html
On the other hand aac works fine in video live streams - but of course those are delivered via rtmp, not like shoutcast over http.

(and yes, I tested again - http://78.24.188.207:7600/;stream.mp3 plays fine in Mplayer)

It still looks a bit suspicious because the mp3 stream plays just fine in Flowplayer.
