### ISSUE TITLE
Seek event is activated on mouseDown instead of mouseUp while dragging

### ISSUE THREAD

**Issue by kasrinat** [flowplayer/flash#174]
Hello,

I have a provider that extends the StreamProvider class and implements it's seek method amongst other things. While investigating an odd seeking behavior with my embedded flow player, I found that the provider's seek method was being triggered on mouseDown instead of mouseUp. This especially causes issues when dragging, with the issues being mainly of the UI kind with the spinning buffer wheel dying out before the actual completion of seek.
I looked at the following file:
plugins/controls/src/actionscript/org/flowplayer/controls/scrubber/ScrubberSlider.as

It seems to use the 'mouseDown' property to seek to the scrubber value in the onDragging() method. Does this not have to be 'mouseUp' instead?

Thanks for looking.

**Comment by kasrinat** [comment]
Any thoughts on the above? Thanks.
The seeking behavior seems to be suited more to progressive download than http streams, where downloading fragments takes additional time. Right now, on dragging the slider, the buffer wheel disappears much quicker than the resuming of playback.

The buffering wheel seems to be active for the duration the 'onBeforeSeek' event is registered. On mouseUp, 'onBeforeSeek' changes to 'onSeek' and the buffer wheel disappears, though the seek has not completed yet.

Can you please confirm this is the case? I did see some http stream specific logic (#403), but this does not seem to address this problem.

**Comment by danrossi** [comment]
there was a bug with a seek end timer with HDS due to how it deals with times when seeking. This has been fixed in the player and in the dev branch now. its best to also get the new hds plugin files also.

**Comment by anssip** [comment]
We will release a new Flowplayer Flash version this week or early next week. All Flash plugins will be part of the release as well. @kasrinat, hopefully you can wait for this release.

You can also test with these:
- http://flash.cdn.dev94.flowplayer.us.s3.amazonaws.com/swf/flowplayer-3.2.17-dev.swf
- http://flash.cdn.dev94.flowplayer.us.s3.amazonaws.com/swf/flowplayer.controls-3.2.15-dev.swf

**Comment by kasrinat** [comment]
Thanks a lot for your responses @anssip and @danrossi. I cloned the dev branch and built the swfs from it. Still seeing the same behavior as before. Probably something I am missing. Going to download the dev swfs linked above and try out.
The new flash version would be great, I can test with that within the coming week as well and give feedback.

**Comment by kasrinat** [comment]
Just wanted to note this. I used the linked dev swfs and still seem to see the described behavior. Below is the use case:
- Open an HDS stream in flow player with the 3.2.17 dev swfs or earlier.
- Click down on the playhead with the intention of dragging along the slider  (the buffer wheel spin starts).
- Mouse up on the playhead at the desired seek target (the buffer wheel spin disappears).
- The content however is still in buffering state, so a temporary freeze is observed until playback resumes. This also happens with clicking on the seek target instead of dragging.

Please correct if I am missing something here. But the solution to this could be as simple as keeping the buffer-wheel spinning until the BUFFER_FULL event instead of onBeforeSeek.

**Comment by danrossi** [comment]
I don't understand what you mean sorry please check here

http://flash.dev94.flowplayer.us/plugins/streaming/httpstreaming.html

Provide a demo page perhaps.

**Comment by kasrinat** [comment]
Thanks a lot for that link. I can see the player there seeking just like I would expect using your httpstreaming plugin. We have a custom provider that extends StreamProvider instead of NetStreamControllingStreamProvider, with a different set of underlying libraries. This provider has to support HTTP streaming along with other streaming protocols.

We are overriding the seek() method and using the clip.dispatchEvent() call to notify the Flow internals about the player seek status. So there is a disconnect between the buffering status (spinning wheel) on the player compared to the netstream handling logic. This is resulting in a momentary freeze after the wheel disappears before the stream resumes.

Any suggestions on how to get around this? I guess you would say 'use the httpstreaming plugin' :)

**Comment by danrossi** [comment]
I still don't understand what you are doing. If there is no problem either supply a page  or I'll close this for now thanks. The seek dispatch is being sent from the scrubber in the controls plugin. And there is a seek timer to dispatch a seek complete status in NetStreamControllingStreamProvider have a look. I'm not sure why its there still and may have to be removed but I just fixed this for HDS.

**Comment by kasrinat** [comment]
You can go ahead and close this issue. I think I have enough info to proceed based on your inputs.
