### ISSUE TITLE
Flow player plugin source compile issue

### ISSUE THREAD

**Issue by arunrajrs** [flowplayer/flash#83]
Hi All,
Can any one help me on compiling flowpalyer source code ?
I was trying to compile controles plugin for my custom color schemes but i couldnot complete it as i am geting the following error,

85: Execute failed: java.io.IOException: Cannot run program ""C:\Usersarun\Downl
oads\flex_sdk_4.5.1.21328A_mpl"\bin\mxmlc.exe": CreateProcess error=2, The syste
m cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:615)
        at org.apache.tools.ant.taskdefs.Execute$Java13CommandLauncher.exec(Exec
ute.java:862)

Can any one help on this?

Thanks in advance,
Arunraj

**Comment by danrossi** [comment]
see here C:\Usersarun\Downloads

**Comment by arunrajrs** [comment]
Hi danrossi,
Thanks for the reply. I have corrected the path and compiled again,but still im getting the same

BUILD FAILED
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
220: The following error occurred while executing this line:
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
32: The following error occurred while executing this line:
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
210: The following error occurred while executing this line:
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
85: Execute failed: java.io.IOException: Cannot run program ""C:\Users\arun\Down
loads\flex_sdk_4.5.1.21328A_mpl"\bin\mxmlc.exe": CreateProcess error=5, Access i
s denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:615)
        at org.apache.tools.ant.taskdefs.Execute$Java13CommandLauncher.exec(Exec
ute.java:862)
..............
............

i am compiling in Windows7. Please let me know if i need to do something with the library path added
in the build.xml file, which is inside "plugins/controls/"  folder.
"......
<property name="library-path" value="src/flash ../../lib/common/src/flash ../content/src/actionscript"/>
...... "

actually i could not see any such path inside the folders.I am working with the flowplayer source files which is having all the folder structures as it says in the documentation http://flash.flowplayer.org/documentation/developer/development-environment.html

please do help me to compile the source files.
Thanks in advance,

Arun

**Comment by danrossi** [comment]
you still have a path issue see the double quotes ? there was also possibly a space too hence why it was wrapping here. 

C:\Users\arun\Downloads\flex_sdk_4.5.1.21328A_mpl"\bin\mxmlc.exe

change it to

C:\Users\arun\Downloads\flex_sdk_4.5.1.21328A_mpl\bin\mxmlc.exe

it might need double escaping try this path if the above doesn't work. 

C:\Users\arun\Downloads\flex_sdk_4.5.1.21328A_mpl\bin\mxmlc.exe

**Comment by arunrajrs** [comment]
yes danrossi, it was my mistakes.
right now im using it as follows,

mxmlc_bin=  C:\Users\arun\Downloads\flex_sdk_4.5.1.21328A_mpl\bin\mxmlc.exe
compc_bin= C:\Users\arun\Downloads\flex_sdk_4.5.1.21328A_mpl\bin\compc.exe
asdoc_bin= C:\Users\arun\Downloads\flex_sdk_4.5.1.21328A_mpl\bin\asdoc.exe
but im still getting issues as ,

BUILD FAILED
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
220: The following error occurred while executing this line:
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
32: The following error occurred while executing this line:
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
210: The following error occurred while executing this line:
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
85: unbalanced quotes in -library-path "C:\Users\arun\Downloads\flex_sdk_4.5.1.2
1328A_mpl\frameworks\libs    src/flash/modern

Actually, i didnt get from where this " src/flash/modern" is comming.
Will be great if you can help me on this.
Thanks a lot in advance,
Arun

**Comment by danrossi** [comment]
flexlibsdir=${flexdir}\frameworks\libs

try this, windows slashes are different to unix. Ive never compiled on windows before.

**Comment by arunrajrs** [comment]
Thanks danrossi for helping.
Unfortunately, i couldn't find out from where the "src/flash/modern"  path being called.
now im getting the following 

BUILD FAILED
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
220: The following error occurred while executing this line:
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
32: The following error occurred while executing this line:
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
210: The following error occurred while executing this line:
C:\Users\arun\Desktop\Eram\flow-player\flash-master\lib\devkit\plugin-build.xml:
85: unbalanced quotes in -library-path "C:\Users\arun\Downloads\flex_sdk_4.5.1.2
1328A_mpl\frameworks\libs      src/flash/modern

Could you please tell me from where this "src/flash/modern"  path getting called ?

here is what iam using now,
flexdir="C:\Users\arun\Downloads\flex_sdk_4.5.1.21328A_mpl\

# change this if you want the compiled plugin to be copied to some dir

deploy_dir=..\..\core
flowplayer_lib=..\..\core\build\flowplayer.swc

# change following to point to .exe files when running on Windows

mxmlc_bin=  C:\Users\arun\Downloads\flex_sdk_4.5.1.21328A_mpl\bin\mxmlc.exe
compc_bin= C:\Users\arun\Downloads\flex_sdk_4.5.1.21328A_mpl\bin\compc.exe
asdoc_bin= C:\Users\arun\Downloads\flex_sdk_4.5.1.21328A_mpl\bin\asdoc.exe

# following can usually be left as they are

flexbindir=${flexdir}\bin
flexlibsdir=${flexdir}\frameworks\libs  
flashplayer_bin= 
framerate=31
bgcolor=0xFFFFFF
width=500
height=350

**Comment by danrossi** [comment]
Try and remove the space here 

mxmlc_bin= C:\

Im not sure what that error means

Are you sure it has a quote like flexdir="C , because its quite possible that.

**Comment by arunrajrs** [comment]
Hi danrossi,
Thanks...thanks a lot.
You saved me!!.
I found that the spacing ,slash (/) and " were the problem.

thanks for the help danrossi.

**Comment by arunrajrs** [comment]
now im able to build the swf without having any problem.

thanks github community for the helps.

**Comment by danrossi** [comment]
ok no problems closing this
